python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 0
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 2
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 3
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 4
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 5
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 6
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 7
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 8
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 9

python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 0
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 2
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 3
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 4
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 5
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 6
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 7
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 8
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset CS --random_seed 9

python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 0
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 2
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 3
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 4
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 5
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 6
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 7
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 8
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Cora --random_seed 9

python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 0
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 2
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 3
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 4
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 5
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 6
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 7
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 8
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Amazon --random_seed 9

python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 0
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 2
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 3
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 4
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 5
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 6
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 7
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 8
python poison_attack.py  --attack label --data_dir /scratch/akshit.sinha/data/ --dataset Computers --random_seed 9
